apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.cluster }}
  project: default
  source:
    chart: metallb
    helm:
      parameters:
        - name: "arpAddresses"
          value: "192.168.16.240/30"
      valueFiles:
      - values.yaml
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 0.12.0
